#include	"all.h"

void putline8_l( int x, int y, unsigned char* tomb, int xsize ) {
	error( "No kene ide jonnie (putline8_l)!" );
}

void getline8_l( int x, int y, unsigned char* tomb, int xsize ) {
	error( "No kene ide jonnie (getline8_l)!" );
}

void kidrawol640( double t, targytomb* ptt, double ugrasnagysag ) {
	error( "No kene ide jonnie (kidrawol640)!" );
	t++;
	ptt++;
	ugrasnagysag++;
}

void close640( void ) {
	error( "No kene ide jonnie (close640)!" );
}

void bgitorol( void ) {
	error( "No kene ide jonnie (bgitorol)!" );
}

int editor( char* name, palyaleiro* pleiro ) {
	error( "No kene ide jonnie (editor)!" );
	name++;
	pleiro++;
	return 1;
}

void putbytes_l( int x, int y, unsigned char* tomb, int xsize ) {
}

void getbytes_l( int x, int y, unsigned char* tomb, int xsize ) {
}

void ppixel_l( int x, int y, int szin ) {
}

int gpixel_l( int x, int y ) {
}


