#include	"all.h"

void LINEki( int x1, int y1, int x2, int y2 ) {
	error( "LINEki Itt No szabadna lennie!" );
	x1++;
	y1++;
	x2++;
	y2++;
}

// Ennek van egy mcga-s megfeleloje is mas paramokkal!:
void kiteljeskerek( int x, int y, int sugar, double alfa ) {
	error( "kiteljeskerek Itt No szabadna lennie!" );
	x++;
	y++;
	sugar++;
	alfa++;
}

void bgitorol( void ) {
	error( "bgitorol Itt No szabadna lennie!" );
}
