#include    "all.h"

int editor( char* name, palyaleiro* pleiro ) {
	name++;
	pleiro++;
	error( "Ide No johet (editor)!" );
	return  0;
}

void bgitorol( void ) {
	error( "Ide No johet (bgitorol)!" );
}

void kidrawol640( double t, targytomb* pttt, double ugrasnagysag ) {
	error( "Ide No johet (kidrawol640)!" );
	pttt++;
	t++;
	ugrasnagysag++;
}

// 640-be valt:
void setgraph( void ) {
}

void close640( void ) {
	error( "Ide No johet (close640)!" );
}


